name: d9-upgrade-status-2
recipe: drupal8
config:
  php: '7.2'
  via: apache:2.4
  webroot: drupal/web
  database: mysql:5.7
  drush: ^8
  xdebug: false

services:
  appserver:
    build:
      - "chmod u+w web/sites/default"
      - "COMPOSER_PROCESS_TIMEOUT=600 composer install"
      - "chmod u+w web/sites/default"

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web

  check:
    service: appserver
    description: Run D9 Upgrade Status Check against your csv
    cmd:
      - 'git checkout master'
      - 'chmod u+w web/sites/default'
      - '/app/d9upgrade_statuscheckall.sh'

  clean:
    service: appserver
    description: Run D9 Upgrade Status Check against your csv
    cmd:
      - 'git checkout master; git branch | grep -v "master" | xargs git branch -D'
      - 'git reset --hard HEAD'
