name: d9-upgrade-status
recipe: drupal8
config:
  php: '7.2'
  via: apache:2.4
  webroot: drupal/web
  database: mysql:5.7
  drush: ^8
  xdebug: false

services:
  appserver:
    build:
      - 'test -d " web/sites/default" && chmod u+w web/sites/default || echo "this must be your first install"'
      - 'composer install'
      - 'chmod u+w web/sites/default'
    overrides:
      environment:
        INPUT: "list.csv"

  web2:
    type: php:7.2
    via: apache
    webroot: web2
    overrides:
      environment:
        INPUT: "list-2.csv"

  web3:
    type: php:7.2
    via: apache
    webroot: web3
    overrides:
      environment:
        INPUT: "list-3.csv"

  web4:
    type: php:7.2
    via: apache
    webroot: web4
    overrides:
      environment:
        INPUT: "list-4.csv"

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush --root=/app/web

  check:
    service: appserver
    description: Run D9 Upgrade Status Check against your csv
    cmd:
      - 'git checkout master'
      - 'chmod u+w web/sites/default'
      - '/app/d9upgrade_statuscheckall.sh'

  clean:
    service: appserver
    description: Run D9 Upgrade Status Check against your csv
    cmd:
      - 'git checkout master; git branch | grep -v "master" | xargs git branch -D'
      - 'git reset --hard HEAD'
